/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClickMove: typeof import('./src/components/ClickMove.vue')['default']
    FileView: typeof import('./src/components/FileView.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
  }
}

// For TSX support
declare global {
  const ClickMove: typeof import('./src/components/ClickMove.vue')['default']
  const FileView: typeof import('./src/components/FileView.vue')['default']
  const MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
}